namespace LivingWorld.Core;

public sealed record PhaseCReadinessReport(
    bool IsReady,
    int SentientGroupCount,
    int OrganicSentientGroupCount,
    int FallbackSentientGroupCount,
    int PersistentSocietyCount,
    int OrganicPersistentSocietyCount,
    int FallbackPersistentSocietyCount,
    int ActiveSocietyBackedPolityCount,
    int LineageCarryingPolityCount,
    int PolityShellCount,
    int SettlementCount,
    int OrganicSettlementCount,
    int FallbackSettlementCount,
    int ViableSettlementCount,
    int PolityCount,
    int OrganicPolityCount,
    int FallbackPolityCount,
    int ViableFocalCandidateCount,
    int OrganicViableFocalCandidateCount,
    int FallbackViableFocalCandidateCount,
    double AveragePolityAge,
    double HistoricalEventDensity,
    IReadOnlyList<string> FailureReasons)
{
    public static PhaseCReadinessReport Empty { get; } = new(
        false,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0.0,
        0.0,
        Array.Empty<string>());
}
